[build]
  publish = "out"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"

# Apple App Site Association用のヘッダー設定
[[headers]]
  for = "/.well-known/apple-app-site-association"
  [headers.values]
    Content-Type = "application/json"
    Cache-Control = "public, max-age=3600"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/apple-app-site-association"  
  [headers.values]
    Content-Type = "application/json"
    Cache-Control = "public, max-age=3600"
    X-Content-Type-Options = "nosniff"

# ルートのapple-app-site-associationを/.well-knownにリダイレクト
[[redirects]]
  from = "/apple-app-site-association"
  to = "/.well-known/apple-app-site-association"
  status = 200
  force = true

# 404ページの設定
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404